SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `foodCache` (
  `timestamp` varchar(128) CHARACTER SET utf8 NOT NULL,
  `dataSource` varchar(128) CHARACTER SET utf8 NOT NULL,
  `date` varchar(128) CHARACTER SET utf8 NOT NULL,
  `price` varchar(128) CHARACTER SET utf8 NOT NULL,
  `data` varchar(16384) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`timestamp`,`dataSource`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
