<?php

namespace App\Parser;

class Strings
{
    public const EXPLODE_NEWLINES = [
        "\n", '<br >', '<br>', '<br/>', '<br />', '< br>', '< br>',
        '< br/>', '< br >', '< br />'
    ];

    public const SEARCH_REPLACE = [
        'dazu &' => 'dazu',
        'TikkaMasala' => 'Tikka Masala',
        'gegrilltes Hühnerfilets' => 'Gegrilltes Hühnerfilet',
        'gegrillte Hühnerfilets' => 'Gegrilltes Hühnerfilet',
        'milder-Currysauce' => 'milder Currysauce',
        'in milde Currysauce' => 'in milder Currysauce',
        'milde-Currysauce' => 'milder Currysauce',
        'Murgh saag' => 'Murgh Saag',
        'Murhg' => 'Murgh',
        'Gemüse bällchan' => 'Gemüsebällchen',
        'Würziger Currysauce' => 'würziger Currysauce',
        ' :' => ':',
        'Curryemüse' => 'Currygemüse',
        'Kokos-Ober-Sauce' => 'Kokos-Obers-Sauce',
        'kokos-Obers-Sauce' => 'Kokos-Obers-Sauce',
        'Hausgemachter' => 'hausgemachter',
        'Gewürsen' => 'Gewürzen',
        'mit Spinatsauce' => 'in Spinatsauce',
        'currysauce' => 'Currysauce',
        'Frisches Karfiol' => 'Frischer Karfiol',
        'Pikaner Currysauce' => 'pikanter Currysauce',
        'würziger Currysauce' => 'Currysauce',
        'Genüse' => 'Gemüse',
        'Lach ' => 'Lachs ',
        'Schnitlauch' => 'Schnittlauch',
        'Eiernockelr' => 'Eiernockerl',
        'Rosti' => 'Rösti',
        'Speckfi sollen' => 'Speckfisolen',
        'Thunfi sch' => 'Thunfisch',
        'Steinpilztaschrln' => 'Steinpilztascherln',
        'cremsuppe' => 'cremesuppe',
        'Gemuse' => 'Gemüse',
        'Szedediner' => 'Szegediner',
        'cemesuppe' => 'cremesuppe',
        'Wurstrfleckerl' => 'Wurstfleckerl',
        'Spare Rips' => 'Spareribs',
        'Gegrillte Hühnerfilet' => 'Gegrilltes Hühnerfilet',
        'Majonnaise' => 'Mayonnaise',
        'Ingwer,Knoblauch' => 'Ingwer, Knoblauch',
        'Paprika.Zwiebel' => 'Paprika, Zwiebel',
        'Zwiebel,Ingwer' => 'Zwiebel, Ingwer',
        'Giegrilltes' => 'Gegrilltes',
        'mit &' => '&',
        'und &' => 'und',
        '( ' => '(',
        ' )' => ')',
        'Gerbratene' => 'Gebratene',
        'Obersauce' => 'Oberssauce',
        'Kartoffeln,Knoblauch' => 'Kartoffeln, Knoblauch',
        'Gegrilltes Hühnerfilets' => 'Gegrilltes Hühnerfleisch',
        '-Hühnerfleisch' => 'Hühnerfleisch',
        'masalasauce' => 'Masalasauce',
        'Bio Spaghetti' => 'Bio-Spaghetti',
        'Geröstetet' => 'Geröstete',
        'Seafood Pie -' => 'Seafood Pie',
        'Artischokensalat' => 'Artischockensalat',
        'Gegrille' => 'Gegrillte',
        'Szegendiner Krautfleisch' => 'Szegediner Krautfleisch',
        'Chili con carne' => 'Chili con Carne',
        'Schweinsrükcesteak' => 'Schweinsrückensteak',
        'khohl' => 'kohl',
        'Ptersil' => 'Petersil',
        'Gemüseuppe' => 'Gemüsesuppe',
        ' , ' => ', ',
        '1/2.' => '1/2', // haas beisl "1/2. brathuhn" fix, because "2." is not allowed
        'gemichtem' => 'gemischtem',
        'Schafskäse&Blattspinat' => 'Schafskäse & Blattspinat',
        '&Croutons' => '& Croutons',
        '"Altes Fassl"mit' => '"Altes Fassl" mit',
        'gebr.Speck' => 'gebr. Speck',
        ', (1/ 0)' => '',
        'Meeeres' => 'Meeres',
        'Eeintropf' => 'Eintropf',
        'Gebackens' => 'Gebackenes',
        'Vegetarischer' => '',
        'Vegetarisches' => '',
        'Vegetarisch' => '',
        'Salateller' => 'Salatteller',
        'Mitwoch' => 'Mittwoch',
        'Rieltte' => 'Rillette',
        'von Schwein' => 'vom Schwein',
        'Nuß' => 'Nuss',
        'tagessuppe oder salat & dessert' => '(tagessuppe | salat) & dessert',
        'Menü 1' => '',
        'Menü 2' => '',
        ' Vegan' => '', // TasteOfIndia info FIXME: move into venue specific parser
    ];
}